Add Glass Enterprise
codyogden/killedbygoogle pull request #1364
Opened 2023-03-15 23:55 UTC by vladikoff

2023-03-18 13:10 UTC, WebSnke requested changes

2023-03-18 13:10 UTC, WebSnke commented on graveyard.json
> +    "link": "https://support.google.com/glass-enterprise/customer/answer/13417888",
> **Please do not use Google Support articles, linking to the product's URL, the product's marketing URL, or other Google-provided links.*

I suggest that we should use [this link](https://www.pcmag.com/news/rip-google-glass-enterprise-as-sales-for-smart-glasses-end) instead as Google Support links are not allowed here.

```suggestion
    "link": "https://www.pcmag.com/news/rip-google-glass-enterprise-as-sales-for-smart-glasses-end",
```

2023-03-18 15:12 UTC, vladikoff commented
@WebSnke updated 👍

2023-03-24 01:45 UTC, vladikoff commented
Preview LGTM!
<img width="1089" alt="Screen Shot 2023-03-23 at 9 44 50 PM" src="https://user-images.githubusercontent.com/128755/227403245-2a12c7ab-66d6-4e44-b89c-3c39eaae96db.png">

2026-04-26 21:34 UTC, codyogden commented
Just going to do this elsewhere. Thanks!

2026-04-26 21:34 UTC, closed without merging